alert("THIS IS JUST A FRONTEND WORK WITH NO BACKEND, SO IT JUST FOR SHOW, IT WON'T WORK LIKE A REAL FACEBOOK AND IT NOT RESPONSIVE SO DON'T YOU EVER TRY TO CHANGE SCREEN SIZE. THAT WHY THIS WILL ONLY LOOK GOOD IN DESKTOP OR LATTOP")

